plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.fbs10.app'
    compileSdk 33

    defaultConfig {
        applicationId "com.fbs10.app"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // تحديد معمارية v8a فقط
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    signingConfigs {
        release {
            storeFile file("fbs10.jks")
            storePassword "fbsfbsfbss"
            keyAlias "fbs10s"
            keyPassword "fbsfbsfbss"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "FBS10-${variant.name}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
}
